#!/bin/bash

# make current script invokable from any directory
BUILD_FILE_PREV_DIR=$(pwd)
BUILD_FILE_DIR=$(dirname ${BASH_SOURCE[0]});
cd $BUILD_FILE_DIR;
BUILD_FILE_DIR=$(pwd)

echo "Running './build $*'"

set -a  # begin exporting all constants automatically
. ./properties/constants true $@;
set +a  # stop exporting all constants automatically

docker compose -f "$DOCKER_COMPOSE_FILE" build $QA_OPTIONS;

cd $BUILD_FILE_PREV_DIR;
