#!/bin/bash

# make current script invokable from any directory
INSTALL_FILE_PREV_DIR=$(pwd)
INSTALL_FILE_DIR=$(dirname ${BASH_SOURCE[0]});
cd $INSTALL_FILE_DIR;
INSTALL_FILE_DIR=$(pwd)

echo "Running './spinup $*'"

set -a  # begin exporting all constants automatically
. ./properties/constants true $@;
set +a  # stop exporting all constants automatically

if [ -f "./$DOCKER_COMPOSE_FILE" ]; then
    [[ $VOLUMES = "true" ]] && options+=" --volumes";

    docker compose -f "$DOCKER_COMPOSE_FILE" down ${options[@]};
    [[ $VOLUMES = true ]] && docker volume rm $(docker volume ls -qf dangling=true) 2>/dev/null

    docker compose -f "$DOCKER_COMPOSE_FILE" up --force-recreate -d --no-build;
fi;
echo "$DOCKER_COMPOSE_FILE";

cd $INSTALL_FILE_PREV_DIR;
